config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "lands/select", to: "lands#select"
  put "lands/select", to: "lands#attach_owner", as: 'land_attach_owner'




  resources :lands do
    resources :bookings, only: [:new, :create]
    resources :land_periodes, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index, :update]
  resources :land_periodes, only: [:index] do
    resources :bookings, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :land_periode
  enum :status, { pending: 0, accepted: 1, rejected: 2, canceled: 3 }
end

app/models/land.rb
class Land < ApplicationRecord
  belongs_to :user, optional: true
  has_many :land_periodes
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  # validates :description, presence: true
end

app/models/land_periode.rb
class LandPeriode < ApplicationRecord
  belongs_to :land
  has_many :bookings
  before_validation :random_price

  def random_price
    self.price = rand(100..1000)
  end

  def available?
    return !(bookings.where(status: 'accepted').exists?)
  end

  def already_rent_by_user?(curr_user_id)
    return bookings.where(user: curr_user_id).exists?
  end

  def periode_for_a_land(land)
    @periodes = LandPeriode.where(land: land)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :land
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  def dictator?
    land.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_notification

  add_flash_types :info, :error, :success

  def after_sign_in_path_for(resource)
    lands_path
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def set_notification
    unless current_user&.dictator?
      @notification = nil
      return
    end
    land_periodes_for_land = current_user.land.land_periodes
    land_periodes_for_land.each do | periode |

      p 'periode is'
      p periode.read
      p ''

      if !periode.read
        @notification = 1
      end
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all.where(user: current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
  end


  def new
  end

  def create
    @booking = Booking.new
    @booking.user = current_user
    @land_periode = LandPeriode.find(params[:land_periode_id])

    puts @land_periode.inspect
    @land_periode.update(read: false)
    puts @land_periode.inspect

    @booking.land_periode = @land_periode

    return if !@land_periode.available? || @land_periode.already_rent_by_user?(current_user.id)

    if @booking.save
      flash[:success] = "Your request has been into concern."
    else
      flash[:alert] = "Something went wrong, try again."
    end
    redirect_to land_path(@land_periode.land)
  end
  # <%= if @land_periode.booked_by_owner?%>

  def update
    p 'update booking'
    p params[:status]
    @booking = Booking.find(params[:id])
    @booking.update(status: params[:status])
    redirect_to land_path(current_user.land.id)
  end

  def accepted_booking?

  end

  private

  def booking_params
    params.require(:booking).permit(:land_periode, :user)
  end

end

app/controllers/land_periodes_controller.rb
class LandPeriodesController < ApplicationController
  def index
    @land_periodes = LandPeriode.all
  end

  def show
  end

  def new
    @land = Land.find(params[:land_id])
    @land_periodes = LandPeriode.new
  end

  def create
    puts "create methode"
    @land_periodes = LandPeriode.new(land_periodes_params)
    @land_periodes.land = current_user.land

    if @land_periodes.save
      redirect_to land_periodes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def land_periodes_params
    params.require(:land_periode).permit(:starts_the, :ends_the, :land_id)
  end

end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  def index
    @lands = Land.where.not(user: nil, user: current_user)
  end

  def show
    @land = Land.find(params[:id])
    @periodes = @land.land_periodes
    @status = current_user.land == @land

    return unless @land == current_user.land
    @periodes.each do |periode|
      periode.update(read: true)
    end

  end

  def new
    @land = Land.new
  end

  def select
    @land = Land
    @lands = Land.where(user: nil).order('name ASC')
  end

  def attach_owner
    @land = Land.find(params[:Land]['land_id'])
    @land.update(user: current_user)
    redirect_to land_path(@land)
  end

  def create
    @land = Land.new(land_params)
    @land.user = current_user
    if @land.save
      redirect_to lands_path
    else
      render :new, status: :unprocessable_entity
    end
  end
private

def land_params
  params.require(:land).permit(:name, :description)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
  <div class="d-flex align-items-center justify-content-between">
    <h1 class='mt-5 mb-5'>My Bookings</h1>
  </div>

<% if @bookings.length > 0 %>
  <% @bookings.each do | booking | %>
    <% @booking_status = booking.status  %>
    <% @class_style = 'background-color: #9cf0b2' if @booking_status == 'accepted'%>
    <% @class_style = 'background-color: #f5e3a4' if @booking_status == 'pending'%>
    <% @class_style = 'background-color: #e3e3e3' if @booking_status == 'rejected'%>
    <div class="card mb-2 mt-2">
      <div class="card-body d-flex justify-content-between"  style="<%= @class_style %>">
        <h5 class="card-title fw-bold flex-column">From: <%= booking.land_periode.starts_the.strftime('%a %d %b %Y') %></h5>
        <h5 class="card-title fw-bold flex-column">To: <%= booking.land_periode.ends_the.strftime('%a %d %b %Y') %></h5>
        <h5 class="card-title "><%= booking.land_periode.land.name %></h5>
        <h5 class="card-title "><%= booking.land_periode.land.user.name %></h5>
        <h5 class="card-title fw-bold"><%= booking.status %></h5>
      </div>
    </div>
  <% end %>
<% else %>
  <p>You don't have bookings yet ...</p>
<% end %>

app/views/bookings/show.html.erb
<h1><%= @booking.status %></h1>
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/land_periodes/index.html.erb
<div class="container mt-5">
  <h1>Your rental period has been taken into account</h1>
  <%# <div class="grid"> %>

  <%# <% @land_periodes.each do | land_periode | %>
  <%# <div class="card"> %>
      <%= link_to "See my rental periods", land_path(current_user.land.id ), class: "btn btn-primary" %>
    <%# </div>
  </div>
  <% end %>

  <%# </div> %>
</div>

app/views/land_periodes/new.html.erb
<h1>Lands Periods</h1>
<%= simple_form_for([@land, @land_periodes]) do |f| %>
  <%= f.input :starts_the %>
  <%= f.input :ends_the %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lands/edit.html.erb
<h1>Select a country</h1>

app/views/lands/index.html.erb
<div class="container mt-5">
  <h1 class='mb-4'>Find a land to lead!</h1>
  <div class="grid">

  <% @lands.each do | land | %>
  <div class="d-flex flex-column card">
    <div class='d-flex img-div'>
      <img src=<%= land.flag %> class="img-flag" alt="flag-image">
    </div>
    <div class="card-body d-flex flex-column justify-content-between">
      <h4 class="card-title fw-bold"><%= land.name %></h4>

      <div class="d-flex justify-content-around mb-2 mt-2">
        <div class="d-flex flex-column align-items-center">
          <i class="fa-solid fa-people-group"></i>
          <span class='fw-bold'><%= land.population %></span>
          <span>people</span>
        </div>

        <div class="d-flex flex-column align-items-center">
          <i class="fa-solid fa-map"></i>
          <span class='fw-bold'><%= land.area %></span>
          <span>km2</span>
        </div>


      </div>
      <div class="d-grid gap-2">
      <%= link_to "See more", land_path(land.id), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <% end %>

  </div>
</div>

app/views/lands/new.html.erb
<div class="container mt-5">
  <%= simple_form_for(@land) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :area %>
    <%= f.input :flag %>
    <%= f.input :population %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lands/select.html.erb
<div class="container">

  <h1>Select your country</h1>

  <%= form_tag land_attach_owner_path, method: :put do %>
    <%= collection_select @land, :land_id, @lands, :id, :name %>
    <%= submit_tag "Validate"%>
  <% end %>

  <%# <%= button_to "Validate", land_path(200), method: :put, class:'btn btn-primary btn-md px-4 me-md-4' %>
</div>

app/views/lands/show.html.erb
<% @owner = User.find(@land.user_id)[:name] %>
<div class="container mb-5">
<div class="d-flex align-items-center">
  <img src="<%= @land.flag%>" alt="flag" width="auto" height="150px">
  <div class='ms-4'>
    <h1 class="mt-4"><%= @land.name %></h1>
    <h5>Owned by : <%= @owner == current_user.name ? 'you' : @owner %></h5>
  </div>
</div>

<% if @status %>
  <div class="d-flex align-items-center justify-content-between">
    <h1 class='mt-5 mb-5'>My rentals periods</h1>
    <%= link_to "Add periodes",new_land_land_periode_path(current_user.land), class: "btn btn-primary" %>
  </div>
    <% @periodes.each do | periode | %>
      <div class='mb-2 mt-2'>
        <div class="d-flex justify-content-between">
          <div class="d-flex justify-content-around">
            <h5 class='me-2'>From:</h5>
            <h5 class='me-2'><strong><%= periode.starts_the %></strong></h5>
            <h5 class='me-2'> to: </h5>
            <h5 class='me-2'><strong><%= periode.ends_the %></strong></h5>
          </div>
        </div>
      </div>

      <% periode.bookings.each do |booking| %>

        <% if booking.status == 'pending' %>
          <div class="card">
            <div class="d-flex flex-row justify-content-between card-body">
              <p>Offer from: <strong><%= booking.user.name %></strong></p>
              <div class='d-flex'>
                <%= button_to "Accept", booking_path(booking), method: :put, params: {status: 'accepted'}, class: "btn btn-outline-success me-4" %>
                <%= button_to "Reject", booking_path(booking), method: :put, params: {status: 'rejected'}, class: "btn btn-outline-warning" %>
              </div>
            </div>
          </div>
        <% elsif booking.status == 'accepted' %>
          <div class="card" style="background-color: #9cf0b2">
            <div class="d-flex flex-row justify-content-between card-body">
              <p>Offer from: <strong><%= booking.user.name %></strong></p>
              <div>
                <%= button_to "Cancel", booking_path(booking.id), method: :put, params: {status: 'pending'}, class: "btn btn-outline-dark" %>
              </div>
            </div>
          </div>
        <% elsif booking.status == 'rejected' %>
          <div class="card" style="background-color: #e3e3e3">
            <div class="d-flex flex-row justify-content-between card-body">
              <p>Offer from: <strong><%= booking.user.name %></strong></p>
              <div>
                <%= button_to "Cancel", booking_path(booking.id), method: :put, params: {status: 'pending'}, class: "btn btn-outline-dark" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if periode.bookings.length < 1 %>
          <div class="card" style="background-color: transparent">
            <div class="d-flex flex-row justify-content-between card-body">
              <p>No offer yet... </p>
            </div>
          </div>
      <% end %>
  <% end %>
<% else %>
  <div class="d-flex align-items-center justify-content-between">
    <h1 class='mt-5 mb-5'>My rentals periods</h1>
  </div>
  <% @periodes.each do |periode| %>
  <% @class_style = '' %>
  <% if periode.already_rent_by_user?(current_user) %>
    <% @booking_status = periode.bookings.find_by(user: current_user).status  %>
    <% @class_style = 'background-color: #9cf0b2' if @booking_status == 'accepted'%>
    <% @class_style = 'background-color: #f5e3a4' if @booking_status == 'pending'%>
    <% @class_style = 'background-color: #e3e3e3' if @booking_status == 'rejected'%>
  <% end %>
      <div class='card mb-2 mt-2'>
        <div class="card-body d-flex justify-content-between align-items-center" style="<%= @class_style %>">
        <div class='d-flex align-items-center'>
          <div class="d-flex justify-content-between flex-column">
            <p style='margin: 10px'><strong>From: <%= periode.starts_the.strftime('%a %d %b %Y') %></strong> <br></p>
            <p style='margin: 10px'><strong>To: <%= periode.ends_the.strftime('%a %d %b %Y') %></strong></p>
          </div>
          <div class="d-flex justify-content-between flex-column align-items-center ms-5">
            <h2> <%= periode.price%> $ </h2>
          </div>
        </div>

          <% if periode.already_rent_by_user?(current_user) %>
            <p><strong><%= @booking_status %></strong></p>
          <% else %>
            <% @class_btn = periode.available? ? 'btn btn-primary' : 'btn btn-primary disabled' %>
            <%= button_to "Rent", land_periode_bookings_path(periode), class: @class_btn, form: { data: { turbo_confirm: 'Are you sure?' } } %>
          <% end %>

        </div>
      </div>
  <% end %>
  <% if @periodes.length < 1 %>
  <p>Sorry no rental periods yet ... </p>
  <h1>🤔</h1>
  <% end %>


<% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DictaRent</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row flex-lg-row-reverse align-items-center g-5 py-5">
  <div class="col-10 col-sm-8 col-lg-6">
    <img src="https://focus.telerama.fr/967x550/100/2021/03/29/ac05de5b-3946-4b60-9cb4-58b9a72461b8.jpg" class="d-block mx-lg-auto img-fluid rounded" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
  </div>
  <div class="col-lg-6">
    <h1 class="display-5 fw-bold lh-1 mb-3">DictaRent</h1>
    <p class="lead">Become a dictator during your vacation and live an unforgettable leadership experience</p>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
      <%= button_to "Register", new_user_registration_path, class:'btn btn-primary btn-lg px-4 me-md-2', method: :get%>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<h1>error message</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>
<% if success %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= success %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class='me-md-4'>
          <%= link_to 'list of lands for rent', lands_path, class:'nav-link'%>
          </li>
          <li class='me-md-4'>
          <%= link_to 'My bookings', bookings_path, class:'nav-link'%>
          </li>
          <% unless current_user.land ? true : false %>
          <li>
          <%= button_to "Rent your Land", lands_select_path, method: :get, class:'btn btn-primary btn-md px-4 me-md-4' %>
          </li>
          <% else %>

          <li class='me-md-4'>

            <button id="custom-btn" type="button" class="btn position-relative nav-link">
              <%= link_to 'My land', land_path(current_user.land.id), method: :get, class:'btn btn-primary' %>
              <% if @notification %>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                <%= @notification %>
                <span class="visually-hidden">unread messages</span>
              </span>
              <% end %>
            </button>
          </li>





          <% end %>
          <li class='nav-link me-md-4'>
            <%= current_user.name %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>